[package]
name = "game"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
starknet = "2.0.0"
lootitems = { path = "../loot" }
survivor = { path = "../adventurer" }
market = { path = "../market" }
obstacles = { path = "../obstacles" }

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
allowed-libfuncs = true



