[package]
name = "game"
version = "0.1.0"

[dependencies]
starknet.workspace = true
loot = { path = "../loot" }
adventurer = { path = "../adventurer" }
market = { path = "../market" }
obstacles = { path = "../obstacles" }
pragma_lib = { git = "https://github.com/astraly-labs/pragma-lib" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.13.0" }

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
allowed-libfuncs = true
