[package]
name = "game"
version = "0.1.0"

[dependencies]
starknet.workspace = true
lootitems = { path = "../loot" }
survivor = { path = "../adventurer" }
market = { path = "../market" }
obstacles = { path = "../obstacles" }
game_entropy = { path = "../game_entropy" }
game_snapshot = { path = "../game_snapshot" }
openzeppelin.workspace = true
golden_token.workspace = true
arcade_account.workspace = true
pragma_lib = { git = "https://github.com/astraly-labs/pragma-lib" }

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
allowed-libfuncs = true
